### ISSUE TITLE
Decide on payment gateway [STRIPE]

### ISSUE THREAD

**Issue by Pyxyll** [Pyxyll/Form-pc#14]
We will need a robust prebuit payment gateway so we dont have to handle any of the security or hosting. decide this based on payment types accepted (Google pay, paypal, apple pay, master card, visa) we will need to comply with the PSD2 directive in order to allow easy payments.

**Comment by Pyxyll** [comment]
I think stripe would be the best solution as it allows for a lot of payment methods, but is very customisable in that regard so we can cut out the likes of American Express. They comply with worldwide payment directives like PSD2 and they take a developer first approach so their documentation is great ! Authorize.net is also in the running however stripes “pay as you go” method is much more appealing at this stage of the project
@AlexSmith11 do you have any other suggestions or would you be happy with stripe ?

**Comment by AlexSmith11** [comment]
You've far more experience here than I as the guys I was with before did all their payment stuff in-house with Magento, and I wouldn't touch that with a bargepole. Stripe sounds v good :D
