### ISSUE TITLE
Style Guides

### ISSUE THREAD

**Issue by AlexSmith11** [Pyxyll/Form-pc#17]
I'm picky about how my code is written :D
I'll probably be looking at making a Prettier file.

Really great and fantastic guide: https://github.com/airbnb/javascript

Gitignore for next.js: https://codeconqueror.com/blog/a-good-gitignore-for-next-js

**Comment by Pyxyll** [comment]
That is perfect, human editable code is where we wanna be.

**Comment by AlexSmith11** [comment]
ESlint & Prettier added to project with the AirBnB standards applied.
