### ISSUE TITLE
Decide web tech (apache or NGINX) [NGINX]

### ISSUE THREAD

**Issue by Pyxyll** [Pyxyll/Form-pc#22]
We need to decide what web server to use. Apache will allow for easier set up but NGINX will have MUCH better performance, and we may. need to use NGINX reverse proxy anyway.

**Comment by Pyxyll** [comment]
@AlexSmith11 I think we should just go for NGINX, it can only server static content however we can use FPM modules if needed to serve dynamic

**Comment by AlexSmith11** [comment]
Nginx sounds like a good idea to me - we can use it as a layer above our Node/Express instillation.
Would go something like this? https://www.youtube.com/watch?v=N6ha6i8jt_8
I'm also extremely keen to use Docker on this, as it would help the dev process soooo damn much. Theres a guy I like who creates a docker/express proj here: https://www.youtube.com/watch?v=eCrv43wQ53A

**Comment by AlexSmith11** [comment]
Don't suppose I could have access & sudo perms for the server? Would really really love to be involved as much as I can with this.
