### ISSUE TITLE
Decide if API or Web Trawler [API]

### ISSUE THREAD

**Issue by AlexSmith11** [Pyxyll/Form-pc#5]
We need to see if there is an API that can provide information on all the various parts we will need to use to build a product. If there is not, we need to look into web trawling!
- [x] Research various PC part API's. Find if they are public and for comercial usage.
- [x] Decide on API or WT.

**Comment by Pyxyll** [comment]
https://novabench.com/api
https://pypi.org/project/pcpartpicker/

Not a lot of public APIs. Scrapers may be the only option here with a filter.

**Comment by AlexSmith11** [comment]
Finally found a good thread @Pyxyll. Important read:
https://www.reddit.com/r/webdev/comments/9k74h6/how_does_pc_part_picker_gather_a_vendors_product/

**Comment by AlexSmith11** [comment]
We can apply to use various companies API's through affiliate programs. This seems the most viable. We will initially apply to Amazons, and expand from there. If we are not able to get perms, we will switch to scraping.
