### ISSUE TITLE
Backend tech [EXPRESS, NGINX]

### ISSUE THREAD

**Issue by AlexSmith11** [Pyxyll/Form-pc#7]
Node, Express, .NET Core..? I would be partial to Node/Express. Do we even need Express though?
Decide this with frontend in mind.
- [x] Compare Node and Express and their abilities on handling fairly small data sets (can only be <1000 PC parts around right?)
- [x] Compare Express and .NET Core. .NET would be a large issue in general due to having to learn it.

**Comment by Pyxyll** [comment]
Id be more partial to Node express.. express to make it slightly faster.

**Comment by AlexSmith11** [comment]
For sure, Express works well with Next and I'd friggen love to learn Node properly.

**Comment by AlexSmith11** [comment]
Explanation on why using both Node & NGINX: https://stackoverflow.com/questions/16770673/using-node-js-only-vs-using-node-js-with-apache-nginx
